#include "glapi/core.h"

void (*gl_get_proc(struct gl_api *api, char const *))(void);

struct gl_core30 *gl_resolve_core30(struct gl_api *api, struct gl_core30 *core)
{
	core->CullFace = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glCullFace");
	core->FrontFace = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glFrontFace");
	core->Hint = (void (APIENTRYP)(GLenum , GLenum ))gl_get_proc(api, "glHint");
	core->LineWidth = (void (APIENTRYP)(GLfloat ))gl_get_proc(api, "glLineWidth");
	core->PointSize = (void (APIENTRYP)(GLfloat ))gl_get_proc(api, "glPointSize");
	core->PolygonMode = (void (APIENTRYP)(GLenum , GLenum ))gl_get_proc(api, "glPolygonMode");
	core->Scissor = (void (APIENTRYP)(GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glScissor");
	core->TexParameterf = (void (APIENTRYP)(GLenum , GLenum , GLfloat ))gl_get_proc(api, "glTexParameterf");
	core->TexParameterfv = (void (APIENTRYP)(GLenum , GLenum , const GLfloat *))gl_get_proc(api, "glTexParameterfv");
	core->TexParameteri = (void (APIENTRYP)(GLenum , GLenum , GLint ))gl_get_proc(api, "glTexParameteri");
	core->TexParameteriv = (void (APIENTRYP)(GLenum , GLenum , const GLint *))gl_get_proc(api, "glTexParameteriv");
	core->TexImage1D = (void (APIENTRYP)(GLenum , GLint , GLint , GLsizei , GLint , GLenum , GLenum , const void *))gl_get_proc(api, "glTexImage1D");
	core->TexImage2D = (void (APIENTRYP)(GLenum , GLint , GLint , GLsizei , GLsizei , GLint , GLenum , GLenum , const void *))gl_get_proc(api, "glTexImage2D");
	core->DrawBuffer = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glDrawBuffer");
	core->Clear = (void (APIENTRYP)(GLbitfield ))gl_get_proc(api, "glClear");
	core->ClearColor = (void (APIENTRYP)(GLfloat , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glClearColor");
	core->ClearStencil = (void (APIENTRYP)(GLint ))gl_get_proc(api, "glClearStencil");
	core->ClearDepth = (void (APIENTRYP)(GLdouble ))gl_get_proc(api, "glClearDepth");
	core->StencilMask = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glStencilMask");
	core->ColorMask = (void (APIENTRYP)(GLboolean , GLboolean , GLboolean , GLboolean ))gl_get_proc(api, "glColorMask");
	core->DepthMask = (void (APIENTRYP)(GLboolean ))gl_get_proc(api, "glDepthMask");
	core->Disable = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glDisable");
	core->Enable = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glEnable");
	core->Finish = (void (APIENTRYP)(void))gl_get_proc(api, "glFinish");
	core->Flush = (void (APIENTRYP)(void))gl_get_proc(api, "glFlush");
	core->BlendFunc = (void (APIENTRYP)(GLenum , GLenum ))gl_get_proc(api, "glBlendFunc");
	core->LogicOp = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glLogicOp");
	core->StencilFunc = (void (APIENTRYP)(GLenum , GLint , GLuint ))gl_get_proc(api, "glStencilFunc");
	core->StencilOp = (void (APIENTRYP)(GLenum , GLenum , GLenum ))gl_get_proc(api, "glStencilOp");
	core->DepthFunc = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glDepthFunc");
	core->PixelStoref = (void (APIENTRYP)(GLenum , GLfloat ))gl_get_proc(api, "glPixelStoref");
	core->PixelStorei = (void (APIENTRYP)(GLenum , GLint ))gl_get_proc(api, "glPixelStorei");
	core->ReadBuffer = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glReadBuffer");
	core->ReadPixels = (void (APIENTRYP)(GLint , GLint , GLsizei , GLsizei , GLenum , GLenum , void *))gl_get_proc(api, "glReadPixels");
	core->GetBooleanv = (void (APIENTRYP)(GLenum , GLboolean *))gl_get_proc(api, "glGetBooleanv");
	core->GetDoublev = (void (APIENTRYP)(GLenum , GLdouble *))gl_get_proc(api, "glGetDoublev");
	core->GetError = (GLenum (APIENTRYP)(void))gl_get_proc(api, "glGetError");
	core->GetFloatv = (void (APIENTRYP)(GLenum , GLfloat *))gl_get_proc(api, "glGetFloatv");
	core->GetIntegerv = (void (APIENTRYP)(GLenum , GLint *))gl_get_proc(api, "glGetIntegerv");
	core->GetString = (const GLubyte *(APIENTRYP)(GLenum ))gl_get_proc(api, "glGetString");
	core->GetTexImage = (void (APIENTRYP)(GLenum , GLint , GLenum , GLenum , void *))gl_get_proc(api, "glGetTexImage");
	core->GetTexParameterfv = (void (APIENTRYP)(GLenum , GLenum , GLfloat *))gl_get_proc(api, "glGetTexParameterfv");
	core->GetTexParameteriv = (void (APIENTRYP)(GLenum , GLenum , GLint *))gl_get_proc(api, "glGetTexParameteriv");
	core->GetTexLevelParameterfv = (void (APIENTRYP)(GLenum , GLint , GLenum , GLfloat *))gl_get_proc(api, "glGetTexLevelParameterfv");
	core->GetTexLevelParameteriv = (void (APIENTRYP)(GLenum , GLint , GLenum , GLint *))gl_get_proc(api, "glGetTexLevelParameteriv");
	core->IsEnabled = (GLboolean (APIENTRYP)(GLenum ))gl_get_proc(api, "glIsEnabled");
	core->DepthRange = (void (APIENTRYP)(GLdouble , GLdouble ))gl_get_proc(api, "glDepthRange");
	core->Viewport = (void (APIENTRYP)(GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glViewport");
	core->DrawArrays = (void (APIENTRYP)(GLenum , GLint , GLsizei ))gl_get_proc(api, "glDrawArrays");
	core->DrawElements = (void (APIENTRYP)(GLenum , GLsizei , GLenum , const void *))gl_get_proc(api, "glDrawElements");
	core->PolygonOffset = (void (APIENTRYP)(GLfloat , GLfloat ))gl_get_proc(api, "glPolygonOffset");
	core->CopyTexImage1D = (void (APIENTRYP)(GLenum , GLint , GLenum , GLint , GLint , GLsizei , GLint ))gl_get_proc(api, "glCopyTexImage1D");
	core->CopyTexImage2D = (void (APIENTRYP)(GLenum , GLint , GLenum , GLint , GLint , GLsizei , GLsizei , GLint ))gl_get_proc(api, "glCopyTexImage2D");
	core->CopyTexSubImage1D = (void (APIENTRYP)(GLenum , GLint , GLint , GLint , GLint , GLsizei ))gl_get_proc(api, "glCopyTexSubImage1D");
	core->CopyTexSubImage2D = (void (APIENTRYP)(GLenum , GLint , GLint , GLint , GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glCopyTexSubImage2D");
	core->TexSubImage1D = (void (APIENTRYP)(GLenum , GLint , GLint , GLsizei , GLenum , GLenum , const void *))gl_get_proc(api, "glTexSubImage1D");
	core->TexSubImage2D = (void (APIENTRYP)(GLenum , GLint , GLint , GLint , GLsizei , GLsizei , GLenum , GLenum , const void *))gl_get_proc(api, "glTexSubImage2D");
	core->BindTexture = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glBindTexture");
	core->DeleteTextures = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteTextures");
	core->GenTextures = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenTextures");
	core->IsTexture = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsTexture");
	core->DrawRangeElements = (void (APIENTRYP)(GLenum , GLuint , GLuint , GLsizei , GLenum , const void *))gl_get_proc(api, "glDrawRangeElements");
	core->TexImage3D = (void (APIENTRYP)(GLenum , GLint , GLint , GLsizei , GLsizei , GLsizei , GLint , GLenum , GLenum , const void *))gl_get_proc(api, "glTexImage3D");
	core->TexSubImage3D = (void (APIENTRYP)(GLenum , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei , GLenum , GLenum , const void *))gl_get_proc(api, "glTexSubImage3D");
	core->CopyTexSubImage3D = (void (APIENTRYP)(GLenum , GLint , GLint , GLint , GLint , GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glCopyTexSubImage3D");
	core->ActiveTexture = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glActiveTexture");
	core->SampleCoverage = (void (APIENTRYP)(GLfloat , GLboolean ))gl_get_proc(api, "glSampleCoverage");
	core->CompressedTexImage3D = (void (APIENTRYP)(GLenum , GLint , GLenum , GLsizei , GLsizei , GLsizei , GLint , GLsizei , const void *))gl_get_proc(api, "glCompressedTexImage3D");
	core->CompressedTexImage2D = (void (APIENTRYP)(GLenum , GLint , GLenum , GLsizei , GLsizei , GLint , GLsizei , const void *))gl_get_proc(api, "glCompressedTexImage2D");
	core->CompressedTexImage1D = (void (APIENTRYP)(GLenum , GLint , GLenum , GLsizei , GLint , GLsizei , const void *))gl_get_proc(api, "glCompressedTexImage1D");
	core->CompressedTexSubImage3D = (void (APIENTRYP)(GLenum , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei , GLenum , GLsizei , const void *))gl_get_proc(api, "glCompressedTexSubImage3D");
	core->CompressedTexSubImage2D = (void (APIENTRYP)(GLenum , GLint , GLint , GLint , GLsizei , GLsizei , GLenum , GLsizei , const void *))gl_get_proc(api, "glCompressedTexSubImage2D");
	core->CompressedTexSubImage1D = (void (APIENTRYP)(GLenum , GLint , GLint , GLsizei , GLenum , GLsizei , const void *))gl_get_proc(api, "glCompressedTexSubImage1D");
	core->GetCompressedTexImage = (void (APIENTRYP)(GLenum , GLint , void *))gl_get_proc(api, "glGetCompressedTexImage");
	core->BlendFuncSeparate = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLenum ))gl_get_proc(api, "glBlendFuncSeparate");
	core->MultiDrawArrays = (void (APIENTRYP)(GLenum , const GLint *, const GLsizei *, GLsizei ))gl_get_proc(api, "glMultiDrawArrays");
	core->MultiDrawElements = (void (APIENTRYP)(GLenum , const GLsizei *, GLenum , const void *const*, GLsizei ))gl_get_proc(api, "glMultiDrawElements");
	core->PointParameterf = (void (APIENTRYP)(GLenum , GLfloat ))gl_get_proc(api, "glPointParameterf");
	core->PointParameterfv = (void (APIENTRYP)(GLenum , const GLfloat *))gl_get_proc(api, "glPointParameterfv");
	core->PointParameteri = (void (APIENTRYP)(GLenum , GLint ))gl_get_proc(api, "glPointParameteri");
	core->PointParameteriv = (void (APIENTRYP)(GLenum , const GLint *))gl_get_proc(api, "glPointParameteriv");
	core->BlendColor = (void (APIENTRYP)(GLfloat , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glBlendColor");
	core->BlendEquation = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glBlendEquation");
	core->GenQueries = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenQueries");
	core->DeleteQueries = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteQueries");
	core->IsQuery = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsQuery");
	core->BeginQuery = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glBeginQuery");
	core->EndQuery = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glEndQuery");
	core->GetQueryiv = (void (APIENTRYP)(GLenum , GLenum , GLint *))gl_get_proc(api, "glGetQueryiv");
	core->GetQueryObjectiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetQueryObjectiv");
	core->GetQueryObjectuiv = (void (APIENTRYP)(GLuint , GLenum , GLuint *))gl_get_proc(api, "glGetQueryObjectuiv");
	core->BindBuffer = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glBindBuffer");
	core->DeleteBuffers = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteBuffers");
	core->GenBuffers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenBuffers");
	core->IsBuffer = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsBuffer");
	core->BufferData = (void (APIENTRYP)(GLenum , GLsizeiptr , const void *, GLenum ))gl_get_proc(api, "glBufferData");
	core->BufferSubData = (void (APIENTRYP)(GLenum , GLintptr , GLsizeiptr , const void *))gl_get_proc(api, "glBufferSubData");
	core->GetBufferSubData = (void (APIENTRYP)(GLenum , GLintptr , GLsizeiptr , void *))gl_get_proc(api, "glGetBufferSubData");
	core->MapBuffer = (void *(APIENTRYP)(GLenum , GLenum ))gl_get_proc(api, "glMapBuffer");
	core->UnmapBuffer = (GLboolean (APIENTRYP)(GLenum ))gl_get_proc(api, "glUnmapBuffer");
	core->GetBufferParameteriv = (void (APIENTRYP)(GLenum , GLenum , GLint *))gl_get_proc(api, "glGetBufferParameteriv");
	core->GetBufferPointerv = (void (APIENTRYP)(GLenum , GLenum , void **))gl_get_proc(api, "glGetBufferPointerv");
	core->BlendEquationSeparate = (void (APIENTRYP)(GLenum , GLenum ))gl_get_proc(api, "glBlendEquationSeparate");
	core->DrawBuffers = (void (APIENTRYP)(GLsizei , const GLenum *))gl_get_proc(api, "glDrawBuffers");
	core->StencilOpSeparate = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLenum ))gl_get_proc(api, "glStencilOpSeparate");
	core->StencilFuncSeparate = (void (APIENTRYP)(GLenum , GLenum , GLint , GLuint ))gl_get_proc(api, "glStencilFuncSeparate");
	core->StencilMaskSeparate = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glStencilMaskSeparate");
	core->AttachShader = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glAttachShader");
	core->BindAttribLocation = (void (APIENTRYP)(GLuint , GLuint , const GLchar *))gl_get_proc(api, "glBindAttribLocation");
	core->CompileShader = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glCompileShader");
	core->CreateProgram = (GLuint (APIENTRYP)(void))gl_get_proc(api, "glCreateProgram");
	core->CreateShader = (GLuint (APIENTRYP)(GLenum ))gl_get_proc(api, "glCreateShader");
	core->DeleteProgram = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glDeleteProgram");
	core->DeleteShader = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glDeleteShader");
	core->DetachShader = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glDetachShader");
	core->DisableVertexAttribArray = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glDisableVertexAttribArray");
	core->EnableVertexAttribArray = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glEnableVertexAttribArray");
	core->GetActiveAttrib = (void (APIENTRYP)(GLuint , GLuint , GLsizei , GLsizei *, GLint *, GLenum *, GLchar *))gl_get_proc(api, "glGetActiveAttrib");
	core->GetActiveUniform = (void (APIENTRYP)(GLuint , GLuint , GLsizei , GLsizei *, GLint *, GLenum *, GLchar *))gl_get_proc(api, "glGetActiveUniform");
	core->GetAttachedShaders = (void (APIENTRYP)(GLuint , GLsizei , GLsizei *, GLuint *))gl_get_proc(api, "glGetAttachedShaders");
	core->GetAttribLocation = (GLint (APIENTRYP)(GLuint , const GLchar *))gl_get_proc(api, "glGetAttribLocation");
	core->GetProgramiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetProgramiv");
	core->GetProgramInfoLog = (void (APIENTRYP)(GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetProgramInfoLog");
	core->GetShaderiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetShaderiv");
	core->GetShaderInfoLog = (void (APIENTRYP)(GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetShaderInfoLog");
	core->GetShaderSource = (void (APIENTRYP)(GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetShaderSource");
	core->GetUniformLocation = (GLint (APIENTRYP)(GLuint , const GLchar *))gl_get_proc(api, "glGetUniformLocation");
	core->GetUniformfv = (void (APIENTRYP)(GLuint , GLint , GLfloat *))gl_get_proc(api, "glGetUniformfv");
	core->GetUniformiv = (void (APIENTRYP)(GLuint , GLint , GLint *))gl_get_proc(api, "glGetUniformiv");
	core->GetVertexAttribdv = (void (APIENTRYP)(GLuint , GLenum , GLdouble *))gl_get_proc(api, "glGetVertexAttribdv");
	core->GetVertexAttribfv = (void (APIENTRYP)(GLuint , GLenum , GLfloat *))gl_get_proc(api, "glGetVertexAttribfv");
	core->GetVertexAttribiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetVertexAttribiv");
	core->GetVertexAttribPointerv = (void (APIENTRYP)(GLuint , GLenum , void **))gl_get_proc(api, "glGetVertexAttribPointerv");
	core->IsProgram = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsProgram");
	core->IsShader = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsShader");
	core->LinkProgram = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glLinkProgram");
	core->ShaderSource = (void (APIENTRYP)(GLuint , GLsizei , const GLchar *const*, const GLint *))gl_get_proc(api, "glShaderSource");
	core->UseProgram = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glUseProgram");
	core->Uniform1f = (void (APIENTRYP)(GLint , GLfloat ))gl_get_proc(api, "glUniform1f");
	core->Uniform2f = (void (APIENTRYP)(GLint , GLfloat , GLfloat ))gl_get_proc(api, "glUniform2f");
	core->Uniform3f = (void (APIENTRYP)(GLint , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glUniform3f");
	core->Uniform4f = (void (APIENTRYP)(GLint , GLfloat , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glUniform4f");
	core->Uniform1i = (void (APIENTRYP)(GLint , GLint ))gl_get_proc(api, "glUniform1i");
	core->Uniform2i = (void (APIENTRYP)(GLint , GLint , GLint ))gl_get_proc(api, "glUniform2i");
	core->Uniform3i = (void (APIENTRYP)(GLint , GLint , GLint , GLint ))gl_get_proc(api, "glUniform3i");
	core->Uniform4i = (void (APIENTRYP)(GLint , GLint , GLint , GLint , GLint ))gl_get_proc(api, "glUniform4i");
	core->Uniform1fv = (void (APIENTRYP)(GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glUniform1fv");
	core->Uniform2fv = (void (APIENTRYP)(GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glUniform2fv");
	core->Uniform3fv = (void (APIENTRYP)(GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glUniform3fv");
	core->Uniform4fv = (void (APIENTRYP)(GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glUniform4fv");
	core->Uniform1iv = (void (APIENTRYP)(GLint , GLsizei , const GLint *))gl_get_proc(api, "glUniform1iv");
	core->Uniform2iv = (void (APIENTRYP)(GLint , GLsizei , const GLint *))gl_get_proc(api, "glUniform2iv");
	core->Uniform3iv = (void (APIENTRYP)(GLint , GLsizei , const GLint *))gl_get_proc(api, "glUniform3iv");
	core->Uniform4iv = (void (APIENTRYP)(GLint , GLsizei , const GLint *))gl_get_proc(api, "glUniform4iv");
	core->UniformMatrix2fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix2fv");
	core->UniformMatrix3fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix3fv");
	core->UniformMatrix4fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix4fv");
	core->ValidateProgram = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glValidateProgram");
	core->VertexAttrib1d = (void (APIENTRYP)(GLuint , GLdouble ))gl_get_proc(api, "glVertexAttrib1d");
	core->VertexAttrib1dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttrib1dv");
	core->VertexAttrib1f = (void (APIENTRYP)(GLuint , GLfloat ))gl_get_proc(api, "glVertexAttrib1f");
	core->VertexAttrib1fv = (void (APIENTRYP)(GLuint , const GLfloat *))gl_get_proc(api, "glVertexAttrib1fv");
	core->VertexAttrib1s = (void (APIENTRYP)(GLuint , GLshort ))gl_get_proc(api, "glVertexAttrib1s");
	core->VertexAttrib1sv = (void (APIENTRYP)(GLuint , const GLshort *))gl_get_proc(api, "glVertexAttrib1sv");
	core->VertexAttrib2d = (void (APIENTRYP)(GLuint , GLdouble , GLdouble ))gl_get_proc(api, "glVertexAttrib2d");
	core->VertexAttrib2dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttrib2dv");
	core->VertexAttrib2f = (void (APIENTRYP)(GLuint , GLfloat , GLfloat ))gl_get_proc(api, "glVertexAttrib2f");
	core->VertexAttrib2fv = (void (APIENTRYP)(GLuint , const GLfloat *))gl_get_proc(api, "glVertexAttrib2fv");
	core->VertexAttrib2s = (void (APIENTRYP)(GLuint , GLshort , GLshort ))gl_get_proc(api, "glVertexAttrib2s");
	core->VertexAttrib2sv = (void (APIENTRYP)(GLuint , const GLshort *))gl_get_proc(api, "glVertexAttrib2sv");
	core->VertexAttrib3d = (void (APIENTRYP)(GLuint , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glVertexAttrib3d");
	core->VertexAttrib3dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttrib3dv");
	core->VertexAttrib3f = (void (APIENTRYP)(GLuint , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glVertexAttrib3f");
	core->VertexAttrib3fv = (void (APIENTRYP)(GLuint , const GLfloat *))gl_get_proc(api, "glVertexAttrib3fv");
	core->VertexAttrib3s = (void (APIENTRYP)(GLuint , GLshort , GLshort , GLshort ))gl_get_proc(api, "glVertexAttrib3s");
	core->VertexAttrib3sv = (void (APIENTRYP)(GLuint , const GLshort *))gl_get_proc(api, "glVertexAttrib3sv");
	core->VertexAttrib4Nbv = (void (APIENTRYP)(GLuint , const GLbyte *))gl_get_proc(api, "glVertexAttrib4Nbv");
	core->VertexAttrib4Niv = (void (APIENTRYP)(GLuint , const GLint *))gl_get_proc(api, "glVertexAttrib4Niv");
	core->VertexAttrib4Nsv = (void (APIENTRYP)(GLuint , const GLshort *))gl_get_proc(api, "glVertexAttrib4Nsv");
	core->VertexAttrib4Nub = (void (APIENTRYP)(GLuint , GLubyte , GLubyte , GLubyte , GLubyte ))gl_get_proc(api, "glVertexAttrib4Nub");
	core->VertexAttrib4Nubv = (void (APIENTRYP)(GLuint , const GLubyte *))gl_get_proc(api, "glVertexAttrib4Nubv");
	core->VertexAttrib4Nuiv = (void (APIENTRYP)(GLuint , const GLuint *))gl_get_proc(api, "glVertexAttrib4Nuiv");
	core->VertexAttrib4Nusv = (void (APIENTRYP)(GLuint , const GLushort *))gl_get_proc(api, "glVertexAttrib4Nusv");
	core->VertexAttrib4bv = (void (APIENTRYP)(GLuint , const GLbyte *))gl_get_proc(api, "glVertexAttrib4bv");
	core->VertexAttrib4d = (void (APIENTRYP)(GLuint , GLdouble , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glVertexAttrib4d");
	core->VertexAttrib4dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttrib4dv");
	core->VertexAttrib4f = (void (APIENTRYP)(GLuint , GLfloat , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glVertexAttrib4f");
	core->VertexAttrib4fv = (void (APIENTRYP)(GLuint , const GLfloat *))gl_get_proc(api, "glVertexAttrib4fv");
	core->VertexAttrib4iv = (void (APIENTRYP)(GLuint , const GLint *))gl_get_proc(api, "glVertexAttrib4iv");
	core->VertexAttrib4s = (void (APIENTRYP)(GLuint , GLshort , GLshort , GLshort , GLshort ))gl_get_proc(api, "glVertexAttrib4s");
	core->VertexAttrib4sv = (void (APIENTRYP)(GLuint , const GLshort *))gl_get_proc(api, "glVertexAttrib4sv");
	core->VertexAttrib4ubv = (void (APIENTRYP)(GLuint , const GLubyte *))gl_get_proc(api, "glVertexAttrib4ubv");
	core->VertexAttrib4uiv = (void (APIENTRYP)(GLuint , const GLuint *))gl_get_proc(api, "glVertexAttrib4uiv");
	core->VertexAttrib4usv = (void (APIENTRYP)(GLuint , const GLushort *))gl_get_proc(api, "glVertexAttrib4usv");
	core->VertexAttribPointer = (void (APIENTRYP)(GLuint , GLint , GLenum , GLboolean , GLsizei , const void *))gl_get_proc(api, "glVertexAttribPointer");
	core->UniformMatrix2x3fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix2x3fv");
	core->UniformMatrix3x2fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix3x2fv");
	core->UniformMatrix2x4fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix2x4fv");
	core->UniformMatrix4x2fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix4x2fv");
	core->UniformMatrix3x4fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix3x4fv");
	core->UniformMatrix4x3fv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glUniformMatrix4x3fv");
	core->ColorMaski = (void (APIENTRYP)(GLuint , GLboolean , GLboolean , GLboolean , GLboolean ))gl_get_proc(api, "glColorMaski");
	core->GetBooleani_v = (void (APIENTRYP)(GLenum , GLuint , GLboolean *))gl_get_proc(api, "glGetBooleani_v");
	core->GetIntegeri_v = (void (APIENTRYP)(GLenum , GLuint , GLint *))gl_get_proc(api, "glGetIntegeri_v");
	core->Enablei = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glEnablei");
	core->Disablei = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glDisablei");
	core->IsEnabledi = (GLboolean (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glIsEnabledi");
	core->BeginTransformFeedback = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glBeginTransformFeedback");
	core->EndTransformFeedback = (void (APIENTRYP)(void))gl_get_proc(api, "glEndTransformFeedback");
	core->BindBufferRange = (void (APIENTRYP)(GLenum , GLuint , GLuint , GLintptr , GLsizeiptr ))gl_get_proc(api, "glBindBufferRange");
	core->BindBufferBase = (void (APIENTRYP)(GLenum , GLuint , GLuint ))gl_get_proc(api, "glBindBufferBase");
	core->TransformFeedbackVaryings = (void (APIENTRYP)(GLuint , GLsizei , const GLchar *const*, GLenum ))gl_get_proc(api, "glTransformFeedbackVaryings");
	core->GetTransformFeedbackVarying = (void (APIENTRYP)(GLuint , GLuint , GLsizei , GLsizei *, GLsizei *, GLenum *, GLchar *))gl_get_proc(api, "glGetTransformFeedbackVarying");
	core->ClampColor = (void (APIENTRYP)(GLenum , GLenum ))gl_get_proc(api, "glClampColor");
	core->BeginConditionalRender = (void (APIENTRYP)(GLuint , GLenum ))gl_get_proc(api, "glBeginConditionalRender");
	core->EndConditionalRender = (void (APIENTRYP)(void))gl_get_proc(api, "glEndConditionalRender");
	core->VertexAttribIPointer = (void (APIENTRYP)(GLuint , GLint , GLenum , GLsizei , const void *))gl_get_proc(api, "glVertexAttribIPointer");
	core->GetVertexAttribIiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetVertexAttribIiv");
	core->GetVertexAttribIuiv = (void (APIENTRYP)(GLuint , GLenum , GLuint *))gl_get_proc(api, "glGetVertexAttribIuiv");
	core->VertexAttribI1i = (void (APIENTRYP)(GLuint , GLint ))gl_get_proc(api, "glVertexAttribI1i");
	core->VertexAttribI2i = (void (APIENTRYP)(GLuint , GLint , GLint ))gl_get_proc(api, "glVertexAttribI2i");
	core->VertexAttribI3i = (void (APIENTRYP)(GLuint , GLint , GLint , GLint ))gl_get_proc(api, "glVertexAttribI3i");
	core->VertexAttribI4i = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint ))gl_get_proc(api, "glVertexAttribI4i");
	core->VertexAttribI1ui = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glVertexAttribI1ui");
	core->VertexAttribI2ui = (void (APIENTRYP)(GLuint , GLuint , GLuint ))gl_get_proc(api, "glVertexAttribI2ui");
	core->VertexAttribI3ui = (void (APIENTRYP)(GLuint , GLuint , GLuint , GLuint ))gl_get_proc(api, "glVertexAttribI3ui");
	core->VertexAttribI4ui = (void (APIENTRYP)(GLuint , GLuint , GLuint , GLuint , GLuint ))gl_get_proc(api, "glVertexAttribI4ui");
	core->VertexAttribI1iv = (void (APIENTRYP)(GLuint , const GLint *))gl_get_proc(api, "glVertexAttribI1iv");
	core->VertexAttribI2iv = (void (APIENTRYP)(GLuint , const GLint *))gl_get_proc(api, "glVertexAttribI2iv");
	core->VertexAttribI3iv = (void (APIENTRYP)(GLuint , const GLint *))gl_get_proc(api, "glVertexAttribI3iv");
	core->VertexAttribI4iv = (void (APIENTRYP)(GLuint , const GLint *))gl_get_proc(api, "glVertexAttribI4iv");
	core->VertexAttribI1uiv = (void (APIENTRYP)(GLuint , const GLuint *))gl_get_proc(api, "glVertexAttribI1uiv");
	core->VertexAttribI2uiv = (void (APIENTRYP)(GLuint , const GLuint *))gl_get_proc(api, "glVertexAttribI2uiv");
	core->VertexAttribI3uiv = (void (APIENTRYP)(GLuint , const GLuint *))gl_get_proc(api, "glVertexAttribI3uiv");
	core->VertexAttribI4uiv = (void (APIENTRYP)(GLuint , const GLuint *))gl_get_proc(api, "glVertexAttribI4uiv");
	core->VertexAttribI4bv = (void (APIENTRYP)(GLuint , const GLbyte *))gl_get_proc(api, "glVertexAttribI4bv");
	core->VertexAttribI4sv = (void (APIENTRYP)(GLuint , const GLshort *))gl_get_proc(api, "glVertexAttribI4sv");
	core->VertexAttribI4ubv = (void (APIENTRYP)(GLuint , const GLubyte *))gl_get_proc(api, "glVertexAttribI4ubv");
	core->VertexAttribI4usv = (void (APIENTRYP)(GLuint , const GLushort *))gl_get_proc(api, "glVertexAttribI4usv");
	core->GetUniformuiv = (void (APIENTRYP)(GLuint , GLint , GLuint *))gl_get_proc(api, "glGetUniformuiv");
	core->BindFragDataLocation = (void (APIENTRYP)(GLuint , GLuint , const GLchar *))gl_get_proc(api, "glBindFragDataLocation");
	core->GetFragDataLocation = (GLint (APIENTRYP)(GLuint , const GLchar *))gl_get_proc(api, "glGetFragDataLocation");
	core->Uniform1ui = (void (APIENTRYP)(GLint , GLuint ))gl_get_proc(api, "glUniform1ui");
	core->Uniform2ui = (void (APIENTRYP)(GLint , GLuint , GLuint ))gl_get_proc(api, "glUniform2ui");
	core->Uniform3ui = (void (APIENTRYP)(GLint , GLuint , GLuint , GLuint ))gl_get_proc(api, "glUniform3ui");
	core->Uniform4ui = (void (APIENTRYP)(GLint , GLuint , GLuint , GLuint , GLuint ))gl_get_proc(api, "glUniform4ui");
	core->Uniform1uiv = (void (APIENTRYP)(GLint , GLsizei , const GLuint *))gl_get_proc(api, "glUniform1uiv");
	core->Uniform2uiv = (void (APIENTRYP)(GLint , GLsizei , const GLuint *))gl_get_proc(api, "glUniform2uiv");
	core->Uniform3uiv = (void (APIENTRYP)(GLint , GLsizei , const GLuint *))gl_get_proc(api, "glUniform3uiv");
	core->Uniform4uiv = (void (APIENTRYP)(GLint , GLsizei , const GLuint *))gl_get_proc(api, "glUniform4uiv");
	core->TexParameterIiv = (void (APIENTRYP)(GLenum , GLenum , const GLint *))gl_get_proc(api, "glTexParameterIiv");
	core->TexParameterIuiv = (void (APIENTRYP)(GLenum , GLenum , const GLuint *))gl_get_proc(api, "glTexParameterIuiv");
	core->GetTexParameterIiv = (void (APIENTRYP)(GLenum , GLenum , GLint *))gl_get_proc(api, "glGetTexParameterIiv");
	core->GetTexParameterIuiv = (void (APIENTRYP)(GLenum , GLenum , GLuint *))gl_get_proc(api, "glGetTexParameterIuiv");
	core->ClearBufferiv = (void (APIENTRYP)(GLenum , GLint , const GLint *))gl_get_proc(api, "glClearBufferiv");
	core->ClearBufferuiv = (void (APIENTRYP)(GLenum , GLint , const GLuint *))gl_get_proc(api, "glClearBufferuiv");
	core->ClearBufferfv = (void (APIENTRYP)(GLenum , GLint , const GLfloat *))gl_get_proc(api, "glClearBufferfv");
	core->ClearBufferfi = (void (APIENTRYP)(GLenum , GLint , GLfloat , GLint ))gl_get_proc(api, "glClearBufferfi");
	core->GetStringi = (const GLubyte *(APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glGetStringi");
	core->IsRenderbuffer = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsRenderbuffer");
	core->BindRenderbuffer = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glBindRenderbuffer");
	core->DeleteRenderbuffers = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteRenderbuffers");
	core->GenRenderbuffers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenRenderbuffers");
	core->RenderbufferStorage = (void (APIENTRYP)(GLenum , GLenum , GLsizei , GLsizei ))gl_get_proc(api, "glRenderbufferStorage");
	core->GetRenderbufferParameteriv = (void (APIENTRYP)(GLenum , GLenum , GLint *))gl_get_proc(api, "glGetRenderbufferParameteriv");
	core->IsFramebuffer = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsFramebuffer");
	core->BindFramebuffer = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glBindFramebuffer");
	core->DeleteFramebuffers = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteFramebuffers");
	core->GenFramebuffers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenFramebuffers");
	core->CheckFramebufferStatus = (GLenum (APIENTRYP)(GLenum ))gl_get_proc(api, "glCheckFramebufferStatus");
	core->FramebufferTexture1D = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLuint , GLint ))gl_get_proc(api, "glFramebufferTexture1D");
	core->FramebufferTexture2D = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLuint , GLint ))gl_get_proc(api, "glFramebufferTexture2D");
	core->FramebufferTexture3D = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLuint , GLint , GLint ))gl_get_proc(api, "glFramebufferTexture3D");
	core->FramebufferRenderbuffer = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLuint ))gl_get_proc(api, "glFramebufferRenderbuffer");
	core->GetFramebufferAttachmentParameteriv = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLint *))gl_get_proc(api, "glGetFramebufferAttachmentParameteriv");
	core->GenerateMipmap = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glGenerateMipmap");
	core->BlitFramebuffer = (void (APIENTRYP)(GLint , GLint , GLint , GLint , GLint , GLint , GLint , GLint , GLbitfield , GLenum ))gl_get_proc(api, "glBlitFramebuffer");
	core->RenderbufferStorageMultisample = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei , GLsizei ))gl_get_proc(api, "glRenderbufferStorageMultisample");
	core->FramebufferTextureLayer = (void (APIENTRYP)(GLenum , GLenum , GLuint , GLint , GLint ))gl_get_proc(api, "glFramebufferTextureLayer");
	core->MapBufferRange = (void *(APIENTRYP)(GLenum , GLintptr , GLsizeiptr , GLbitfield ))gl_get_proc(api, "glMapBufferRange");
	core->FlushMappedBufferRange = (void (APIENTRYP)(GLenum , GLintptr , GLsizeiptr ))gl_get_proc(api, "glFlushMappedBufferRange");
	core->BindVertexArray = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glBindVertexArray");
	core->DeleteVertexArrays = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteVertexArrays");
	core->GenVertexArrays = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenVertexArrays");
	core->IsVertexArray = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsVertexArray");

	return core;
}

struct gl_core31 *gl_resolve_core31(struct gl_api *api, struct gl_core31 *core)
{
	union gl_combined_core31 *u = (union gl_combined_core31 *)core;
	(void)gl_resolve_core30(api, &u->core30);

	u->core31.DrawArraysInstanced = (void (APIENTRYP)(GLenum , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glDrawArraysInstanced");
	u->core31.DrawElementsInstanced = (void (APIENTRYP)(GLenum , GLsizei , GLenum , const void *, GLsizei ))gl_get_proc(api, "glDrawElementsInstanced");
	u->core31.TexBuffer = (void (APIENTRYP)(GLenum , GLenum , GLuint ))gl_get_proc(api, "glTexBuffer");
	u->core31.PrimitiveRestartIndex = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glPrimitiveRestartIndex");
	u->core31.CopyBufferSubData = (void (APIENTRYP)(GLenum , GLenum , GLintptr , GLintptr , GLsizeiptr ))gl_get_proc(api, "glCopyBufferSubData");
	u->core31.GetUniformIndices = (void (APIENTRYP)(GLuint , GLsizei , const GLchar *const*, GLuint *))gl_get_proc(api, "glGetUniformIndices");
	u->core31.GetActiveUniformsiv = (void (APIENTRYP)(GLuint , GLsizei , const GLuint *, GLenum , GLint *))gl_get_proc(api, "glGetActiveUniformsiv");
	u->core31.GetActiveUniformName = (void (APIENTRYP)(GLuint , GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetActiveUniformName");
	u->core31.GetUniformBlockIndex = (GLuint (APIENTRYP)(GLuint , const GLchar *))gl_get_proc(api, "glGetUniformBlockIndex");
	u->core31.GetActiveUniformBlockiv = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLint *))gl_get_proc(api, "glGetActiveUniformBlockiv");
	u->core31.GetActiveUniformBlockName = (void (APIENTRYP)(GLuint , GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetActiveUniformBlockName");
	u->core31.UniformBlockBinding = (void (APIENTRYP)(GLuint , GLuint , GLuint ))gl_get_proc(api, "glUniformBlockBinding");

	return core;
}

struct gl_core32 *gl_resolve_core32(struct gl_api *api, struct gl_core32 *core)
{
	union gl_combined_core32 *u = (union gl_combined_core32 *)core;
	(void)gl_resolve_core31(api, &u->core31);

	u->core32.DrawElementsBaseVertex = (void (APIENTRYP)(GLenum , GLsizei , GLenum , const void *, GLint ))gl_get_proc(api, "glDrawElementsBaseVertex");
	u->core32.DrawRangeElementsBaseVertex = (void (APIENTRYP)(GLenum , GLuint , GLuint , GLsizei , GLenum , const void *, GLint ))gl_get_proc(api, "glDrawRangeElementsBaseVertex");
	u->core32.DrawElementsInstancedBaseVertex = (void (APIENTRYP)(GLenum , GLsizei , GLenum , const void *, GLsizei , GLint ))gl_get_proc(api, "glDrawElementsInstancedBaseVertex");
	u->core32.MultiDrawElementsBaseVertex = (void (APIENTRYP)(GLenum , const GLsizei *, GLenum , const void *const*, GLsizei , const GLint *))gl_get_proc(api, "glMultiDrawElementsBaseVertex");
	u->core32.ProvokingVertex = (void (APIENTRYP)(GLenum ))gl_get_proc(api, "glProvokingVertex");
	u->core32.FenceSync = (GLsync (APIENTRYP)(GLenum , GLbitfield ))gl_get_proc(api, "glFenceSync");
	u->core32.IsSync = (GLboolean (APIENTRYP)(GLsync ))gl_get_proc(api, "glIsSync");
	u->core32.DeleteSync = (void (APIENTRYP)(GLsync ))gl_get_proc(api, "glDeleteSync");
	u->core32.ClientWaitSync = (GLenum (APIENTRYP)(GLsync , GLbitfield , GLuint64 ))gl_get_proc(api, "glClientWaitSync");
	u->core32.WaitSync = (void (APIENTRYP)(GLsync , GLbitfield , GLuint64 ))gl_get_proc(api, "glWaitSync");
	u->core32.GetInteger64v = (void (APIENTRYP)(GLenum , GLint64 *))gl_get_proc(api, "glGetInteger64v");
	u->core32.GetSynciv = (void (APIENTRYP)(GLsync , GLenum , GLsizei , GLsizei *, GLint *))gl_get_proc(api, "glGetSynciv");
	u->core32.GetInteger64i_v = (void (APIENTRYP)(GLenum , GLuint , GLint64 *))gl_get_proc(api, "glGetInteger64i_v");
	u->core32.GetBufferParameteri64v = (void (APIENTRYP)(GLenum , GLenum , GLint64 *))gl_get_proc(api, "glGetBufferParameteri64v");
	u->core32.FramebufferTexture = (void (APIENTRYP)(GLenum , GLenum , GLuint , GLint ))gl_get_proc(api, "glFramebufferTexture");
	u->core32.TexImage2DMultisample = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei , GLsizei , GLboolean ))gl_get_proc(api, "glTexImage2DMultisample");
	u->core32.TexImage3DMultisample = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei , GLsizei , GLsizei , GLboolean ))gl_get_proc(api, "glTexImage3DMultisample");
	u->core32.GetMultisamplefv = (void (APIENTRYP)(GLenum , GLuint , GLfloat *))gl_get_proc(api, "glGetMultisamplefv");
	u->core32.SampleMaski = (void (APIENTRYP)(GLuint , GLbitfield ))gl_get_proc(api, "glSampleMaski");

	return core;
}

struct gl_core33 *gl_resolve_core33(struct gl_api *api, struct gl_core33 *core)
{
	union gl_combined_core33 *u = (union gl_combined_core33 *)core;
	(void)gl_resolve_core32(api, &u->core32);

	u->core33.BindFragDataLocationIndexed = (void (APIENTRYP)(GLuint , GLuint , GLuint , const GLchar *))gl_get_proc(api, "glBindFragDataLocationIndexed");
	u->core33.GetFragDataIndex = (GLint (APIENTRYP)(GLuint , const GLchar *))gl_get_proc(api, "glGetFragDataIndex");
	u->core33.GenSamplers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenSamplers");
	u->core33.DeleteSamplers = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteSamplers");
	u->core33.IsSampler = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsSampler");
	u->core33.BindSampler = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glBindSampler");
	u->core33.SamplerParameteri = (void (APIENTRYP)(GLuint , GLenum , GLint ))gl_get_proc(api, "glSamplerParameteri");
	u->core33.SamplerParameteriv = (void (APIENTRYP)(GLuint , GLenum , const GLint *))gl_get_proc(api, "glSamplerParameteriv");
	u->core33.SamplerParameterf = (void (APIENTRYP)(GLuint , GLenum , GLfloat ))gl_get_proc(api, "glSamplerParameterf");
	u->core33.SamplerParameterfv = (void (APIENTRYP)(GLuint , GLenum , const GLfloat *))gl_get_proc(api, "glSamplerParameterfv");
	u->core33.SamplerParameterIiv = (void (APIENTRYP)(GLuint , GLenum , const GLint *))gl_get_proc(api, "glSamplerParameterIiv");
	u->core33.SamplerParameterIuiv = (void (APIENTRYP)(GLuint , GLenum , const GLuint *))gl_get_proc(api, "glSamplerParameterIuiv");
	u->core33.GetSamplerParameteriv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetSamplerParameteriv");
	u->core33.GetSamplerParameterIiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetSamplerParameterIiv");
	u->core33.GetSamplerParameterfv = (void (APIENTRYP)(GLuint , GLenum , GLfloat *))gl_get_proc(api, "glGetSamplerParameterfv");
	u->core33.GetSamplerParameterIuiv = (void (APIENTRYP)(GLuint , GLenum , GLuint *))gl_get_proc(api, "glGetSamplerParameterIuiv");
	u->core33.QueryCounter = (void (APIENTRYP)(GLuint , GLenum ))gl_get_proc(api, "glQueryCounter");
	u->core33.GetQueryObjecti64v = (void (APIENTRYP)(GLuint , GLenum , GLint64 *))gl_get_proc(api, "glGetQueryObjecti64v");
	u->core33.GetQueryObjectui64v = (void (APIENTRYP)(GLuint , GLenum , GLuint64 *))gl_get_proc(api, "glGetQueryObjectui64v");
	u->core33.VertexAttribDivisor = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glVertexAttribDivisor");
	u->core33.VertexAttribP1ui = (void (APIENTRYP)(GLuint , GLenum , GLboolean , GLuint ))gl_get_proc(api, "glVertexAttribP1ui");
	u->core33.VertexAttribP1uiv = (void (APIENTRYP)(GLuint , GLenum , GLboolean , const GLuint *))gl_get_proc(api, "glVertexAttribP1uiv");
	u->core33.VertexAttribP2ui = (void (APIENTRYP)(GLuint , GLenum , GLboolean , GLuint ))gl_get_proc(api, "glVertexAttribP2ui");
	u->core33.VertexAttribP2uiv = (void (APIENTRYP)(GLuint , GLenum , GLboolean , const GLuint *))gl_get_proc(api, "glVertexAttribP2uiv");
	u->core33.VertexAttribP3ui = (void (APIENTRYP)(GLuint , GLenum , GLboolean , GLuint ))gl_get_proc(api, "glVertexAttribP3ui");
	u->core33.VertexAttribP3uiv = (void (APIENTRYP)(GLuint , GLenum , GLboolean , const GLuint *))gl_get_proc(api, "glVertexAttribP3uiv");
	u->core33.VertexAttribP4ui = (void (APIENTRYP)(GLuint , GLenum , GLboolean , GLuint ))gl_get_proc(api, "glVertexAttribP4ui");
	u->core33.VertexAttribP4uiv = (void (APIENTRYP)(GLuint , GLenum , GLboolean , const GLuint *))gl_get_proc(api, "glVertexAttribP4uiv");

	return core;
}

struct gl_core40 *gl_resolve_core40(struct gl_api *api, struct gl_core40 *core)
{
	union gl_combined_core40 *u = (union gl_combined_core40 *)core;
	(void)gl_resolve_core33(api, &u->core33);

	u->core40.MinSampleShading = (void (APIENTRYP)(GLfloat ))gl_get_proc(api, "glMinSampleShading");
	u->core40.BlendEquationi = (void (APIENTRYP)(GLuint , GLenum ))gl_get_proc(api, "glBlendEquationi");
	u->core40.BlendEquationSeparatei = (void (APIENTRYP)(GLuint , GLenum , GLenum ))gl_get_proc(api, "glBlendEquationSeparatei");
	u->core40.BlendFunci = (void (APIENTRYP)(GLuint , GLenum , GLenum ))gl_get_proc(api, "glBlendFunci");
	u->core40.BlendFuncSeparatei = (void (APIENTRYP)(GLuint , GLenum , GLenum , GLenum , GLenum ))gl_get_proc(api, "glBlendFuncSeparatei");
	u->core40.DrawArraysIndirect = (void (APIENTRYP)(GLenum , const void *))gl_get_proc(api, "glDrawArraysIndirect");
	u->core40.DrawElementsIndirect = (void (APIENTRYP)(GLenum , GLenum , const void *))gl_get_proc(api, "glDrawElementsIndirect");
	u->core40.Uniform1d = (void (APIENTRYP)(GLint , GLdouble ))gl_get_proc(api, "glUniform1d");
	u->core40.Uniform2d = (void (APIENTRYP)(GLint , GLdouble , GLdouble ))gl_get_proc(api, "glUniform2d");
	u->core40.Uniform3d = (void (APIENTRYP)(GLint , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glUniform3d");
	u->core40.Uniform4d = (void (APIENTRYP)(GLint , GLdouble , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glUniform4d");
	u->core40.Uniform1dv = (void (APIENTRYP)(GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glUniform1dv");
	u->core40.Uniform2dv = (void (APIENTRYP)(GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glUniform2dv");
	u->core40.Uniform3dv = (void (APIENTRYP)(GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glUniform3dv");
	u->core40.Uniform4dv = (void (APIENTRYP)(GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glUniform4dv");
	u->core40.UniformMatrix2dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix2dv");
	u->core40.UniformMatrix3dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix3dv");
	u->core40.UniformMatrix4dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix4dv");
	u->core40.UniformMatrix2x3dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix2x3dv");
	u->core40.UniformMatrix2x4dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix2x4dv");
	u->core40.UniformMatrix3x2dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix3x2dv");
	u->core40.UniformMatrix3x4dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix3x4dv");
	u->core40.UniformMatrix4x2dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix4x2dv");
	u->core40.UniformMatrix4x3dv = (void (APIENTRYP)(GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glUniformMatrix4x3dv");
	u->core40.GetUniformdv = (void (APIENTRYP)(GLuint , GLint , GLdouble *))gl_get_proc(api, "glGetUniformdv");
	u->core40.GetSubroutineUniformLocation = (GLint (APIENTRYP)(GLuint , GLenum , const GLchar *))gl_get_proc(api, "glGetSubroutineUniformLocation");
	u->core40.GetSubroutineIndex = (GLuint (APIENTRYP)(GLuint , GLenum , const GLchar *))gl_get_proc(api, "glGetSubroutineIndex");
	u->core40.GetActiveSubroutineUniformiv = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLenum , GLint *))gl_get_proc(api, "glGetActiveSubroutineUniformiv");
	u->core40.GetActiveSubroutineUniformName = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetActiveSubroutineUniformName");
	u->core40.GetActiveSubroutineName = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetActiveSubroutineName");
	u->core40.UniformSubroutinesuiv = (void (APIENTRYP)(GLenum , GLsizei , const GLuint *))gl_get_proc(api, "glUniformSubroutinesuiv");
	u->core40.GetUniformSubroutineuiv = (void (APIENTRYP)(GLenum , GLint , GLuint *))gl_get_proc(api, "glGetUniformSubroutineuiv");
	u->core40.GetProgramStageiv = (void (APIENTRYP)(GLuint , GLenum , GLenum , GLint *))gl_get_proc(api, "glGetProgramStageiv");
	u->core40.PatchParameteri = (void (APIENTRYP)(GLenum , GLint ))gl_get_proc(api, "glPatchParameteri");
	u->core40.PatchParameterfv = (void (APIENTRYP)(GLenum , const GLfloat *))gl_get_proc(api, "glPatchParameterfv");
	u->core40.BindTransformFeedback = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glBindTransformFeedback");
	u->core40.DeleteTransformFeedbacks = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteTransformFeedbacks");
	u->core40.GenTransformFeedbacks = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenTransformFeedbacks");
	u->core40.IsTransformFeedback = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsTransformFeedback");
	u->core40.PauseTransformFeedback = (void (APIENTRYP)(void))gl_get_proc(api, "glPauseTransformFeedback");
	u->core40.ResumeTransformFeedback = (void (APIENTRYP)(void))gl_get_proc(api, "glResumeTransformFeedback");
	u->core40.DrawTransformFeedback = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glDrawTransformFeedback");
	u->core40.DrawTransformFeedbackStream = (void (APIENTRYP)(GLenum , GLuint , GLuint ))gl_get_proc(api, "glDrawTransformFeedbackStream");
	u->core40.BeginQueryIndexed = (void (APIENTRYP)(GLenum , GLuint , GLuint ))gl_get_proc(api, "glBeginQueryIndexed");
	u->core40.EndQueryIndexed = (void (APIENTRYP)(GLenum , GLuint ))gl_get_proc(api, "glEndQueryIndexed");
	u->core40.GetQueryIndexediv = (void (APIENTRYP)(GLenum , GLuint , GLenum , GLint *))gl_get_proc(api, "glGetQueryIndexediv");

	return core;
}

struct gl_core41 *gl_resolve_core41(struct gl_api *api, struct gl_core41 *core)
{
	union gl_combined_core41 *u = (union gl_combined_core41 *)core;
	(void)gl_resolve_core40(api, &u->core40);

	u->core41.ReleaseShaderCompiler = (void (APIENTRYP)(void))gl_get_proc(api, "glReleaseShaderCompiler");
	u->core41.ShaderBinary = (void (APIENTRYP)(GLsizei , const GLuint *, GLenum , const void *, GLsizei ))gl_get_proc(api, "glShaderBinary");
	u->core41.GetShaderPrecisionFormat = (void (APIENTRYP)(GLenum , GLenum , GLint *, GLint *))gl_get_proc(api, "glGetShaderPrecisionFormat");
	u->core41.DepthRangef = (void (APIENTRYP)(GLfloat , GLfloat ))gl_get_proc(api, "glDepthRangef");
	u->core41.ClearDepthf = (void (APIENTRYP)(GLfloat ))gl_get_proc(api, "glClearDepthf");
	u->core41.GetProgramBinary = (void (APIENTRYP)(GLuint , GLsizei , GLsizei *, GLenum *, void *))gl_get_proc(api, "glGetProgramBinary");
	u->core41.ProgramBinary = (void (APIENTRYP)(GLuint , GLenum , const void *, GLsizei ))gl_get_proc(api, "glProgramBinary");
	u->core41.ProgramParameteri = (void (APIENTRYP)(GLuint , GLenum , GLint ))gl_get_proc(api, "glProgramParameteri");
	u->core41.UseProgramStages = (void (APIENTRYP)(GLuint , GLbitfield , GLuint ))gl_get_proc(api, "glUseProgramStages");
	u->core41.ActiveShaderProgram = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glActiveShaderProgram");
	u->core41.CreateShaderProgramv = (GLuint (APIENTRYP)(GLenum , GLsizei , const GLchar *const*))gl_get_proc(api, "glCreateShaderProgramv");
	u->core41.BindProgramPipeline = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glBindProgramPipeline");
	u->core41.DeleteProgramPipelines = (void (APIENTRYP)(GLsizei , const GLuint *))gl_get_proc(api, "glDeleteProgramPipelines");
	u->core41.GenProgramPipelines = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glGenProgramPipelines");
	u->core41.IsProgramPipeline = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glIsProgramPipeline");
	u->core41.GetProgramPipelineiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetProgramPipelineiv");
	u->core41.ProgramUniform1i = (void (APIENTRYP)(GLuint , GLint , GLint ))gl_get_proc(api, "glProgramUniform1i");
	u->core41.ProgramUniform1iv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLint *))gl_get_proc(api, "glProgramUniform1iv");
	u->core41.ProgramUniform1f = (void (APIENTRYP)(GLuint , GLint , GLfloat ))gl_get_proc(api, "glProgramUniform1f");
	u->core41.ProgramUniform1fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glProgramUniform1fv");
	u->core41.ProgramUniform1d = (void (APIENTRYP)(GLuint , GLint , GLdouble ))gl_get_proc(api, "glProgramUniform1d");
	u->core41.ProgramUniform1dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glProgramUniform1dv");
	u->core41.ProgramUniform1ui = (void (APIENTRYP)(GLuint , GLint , GLuint ))gl_get_proc(api, "glProgramUniform1ui");
	u->core41.ProgramUniform1uiv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLuint *))gl_get_proc(api, "glProgramUniform1uiv");
	u->core41.ProgramUniform2i = (void (APIENTRYP)(GLuint , GLint , GLint , GLint ))gl_get_proc(api, "glProgramUniform2i");
	u->core41.ProgramUniform2iv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLint *))gl_get_proc(api, "glProgramUniform2iv");
	u->core41.ProgramUniform2f = (void (APIENTRYP)(GLuint , GLint , GLfloat , GLfloat ))gl_get_proc(api, "glProgramUniform2f");
	u->core41.ProgramUniform2fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glProgramUniform2fv");
	u->core41.ProgramUniform2d = (void (APIENTRYP)(GLuint , GLint , GLdouble , GLdouble ))gl_get_proc(api, "glProgramUniform2d");
	u->core41.ProgramUniform2dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glProgramUniform2dv");
	u->core41.ProgramUniform2ui = (void (APIENTRYP)(GLuint , GLint , GLuint , GLuint ))gl_get_proc(api, "glProgramUniform2ui");
	u->core41.ProgramUniform2uiv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLuint *))gl_get_proc(api, "glProgramUniform2uiv");
	u->core41.ProgramUniform3i = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint ))gl_get_proc(api, "glProgramUniform3i");
	u->core41.ProgramUniform3iv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLint *))gl_get_proc(api, "glProgramUniform3iv");
	u->core41.ProgramUniform3f = (void (APIENTRYP)(GLuint , GLint , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glProgramUniform3f");
	u->core41.ProgramUniform3fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glProgramUniform3fv");
	u->core41.ProgramUniform3d = (void (APIENTRYP)(GLuint , GLint , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glProgramUniform3d");
	u->core41.ProgramUniform3dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glProgramUniform3dv");
	u->core41.ProgramUniform3ui = (void (APIENTRYP)(GLuint , GLint , GLuint , GLuint , GLuint ))gl_get_proc(api, "glProgramUniform3ui");
	u->core41.ProgramUniform3uiv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLuint *))gl_get_proc(api, "glProgramUniform3uiv");
	u->core41.ProgramUniform4i = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLint ))gl_get_proc(api, "glProgramUniform4i");
	u->core41.ProgramUniform4iv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLint *))gl_get_proc(api, "glProgramUniform4iv");
	u->core41.ProgramUniform4f = (void (APIENTRYP)(GLuint , GLint , GLfloat , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glProgramUniform4f");
	u->core41.ProgramUniform4fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLfloat *))gl_get_proc(api, "glProgramUniform4fv");
	u->core41.ProgramUniform4d = (void (APIENTRYP)(GLuint , GLint , GLdouble , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glProgramUniform4d");
	u->core41.ProgramUniform4dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLdouble *))gl_get_proc(api, "glProgramUniform4dv");
	u->core41.ProgramUniform4ui = (void (APIENTRYP)(GLuint , GLint , GLuint , GLuint , GLuint , GLuint ))gl_get_proc(api, "glProgramUniform4ui");
	u->core41.ProgramUniform4uiv = (void (APIENTRYP)(GLuint , GLint , GLsizei , const GLuint *))gl_get_proc(api, "glProgramUniform4uiv");
	u->core41.ProgramUniformMatrix2fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix2fv");
	u->core41.ProgramUniformMatrix3fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix3fv");
	u->core41.ProgramUniformMatrix4fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix4fv");
	u->core41.ProgramUniformMatrix2dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix2dv");
	u->core41.ProgramUniformMatrix3dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix3dv");
	u->core41.ProgramUniformMatrix4dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix4dv");
	u->core41.ProgramUniformMatrix2x3fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix2x3fv");
	u->core41.ProgramUniformMatrix3x2fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix3x2fv");
	u->core41.ProgramUniformMatrix2x4fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix2x4fv");
	u->core41.ProgramUniformMatrix4x2fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix4x2fv");
	u->core41.ProgramUniformMatrix3x4fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix3x4fv");
	u->core41.ProgramUniformMatrix4x3fv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLfloat *))gl_get_proc(api, "glProgramUniformMatrix4x3fv");
	u->core41.ProgramUniformMatrix2x3dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix2x3dv");
	u->core41.ProgramUniformMatrix3x2dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix3x2dv");
	u->core41.ProgramUniformMatrix2x4dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix2x4dv");
	u->core41.ProgramUniformMatrix4x2dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix4x2dv");
	u->core41.ProgramUniformMatrix3x4dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix3x4dv");
	u->core41.ProgramUniformMatrix4x3dv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLboolean , const GLdouble *))gl_get_proc(api, "glProgramUniformMatrix4x3dv");
	u->core41.ValidateProgramPipeline = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glValidateProgramPipeline");
	u->core41.GetProgramPipelineInfoLog = (void (APIENTRYP)(GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetProgramPipelineInfoLog");
	u->core41.VertexAttribL1d = (void (APIENTRYP)(GLuint , GLdouble ))gl_get_proc(api, "glVertexAttribL1d");
	u->core41.VertexAttribL2d = (void (APIENTRYP)(GLuint , GLdouble , GLdouble ))gl_get_proc(api, "glVertexAttribL2d");
	u->core41.VertexAttribL3d = (void (APIENTRYP)(GLuint , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glVertexAttribL3d");
	u->core41.VertexAttribL4d = (void (APIENTRYP)(GLuint , GLdouble , GLdouble , GLdouble , GLdouble ))gl_get_proc(api, "glVertexAttribL4d");
	u->core41.VertexAttribL1dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttribL1dv");
	u->core41.VertexAttribL2dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttribL2dv");
	u->core41.VertexAttribL3dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttribL3dv");
	u->core41.VertexAttribL4dv = (void (APIENTRYP)(GLuint , const GLdouble *))gl_get_proc(api, "glVertexAttribL4dv");
	u->core41.VertexAttribLPointer = (void (APIENTRYP)(GLuint , GLint , GLenum , GLsizei , const void *))gl_get_proc(api, "glVertexAttribLPointer");
	u->core41.GetVertexAttribLdv = (void (APIENTRYP)(GLuint , GLenum , GLdouble *))gl_get_proc(api, "glGetVertexAttribLdv");
	u->core41.ViewportArrayv = (void (APIENTRYP)(GLuint , GLsizei , const GLfloat *))gl_get_proc(api, "glViewportArrayv");
	u->core41.ViewportIndexedf = (void (APIENTRYP)(GLuint , GLfloat , GLfloat , GLfloat , GLfloat ))gl_get_proc(api, "glViewportIndexedf");
	u->core41.ViewportIndexedfv = (void (APIENTRYP)(GLuint , const GLfloat *))gl_get_proc(api, "glViewportIndexedfv");
	u->core41.ScissorArrayv = (void (APIENTRYP)(GLuint , GLsizei , const GLint *))gl_get_proc(api, "glScissorArrayv");
	u->core41.ScissorIndexed = (void (APIENTRYP)(GLuint , GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glScissorIndexed");
	u->core41.ScissorIndexedv = (void (APIENTRYP)(GLuint , const GLint *))gl_get_proc(api, "glScissorIndexedv");
	u->core41.DepthRangeArrayv = (void (APIENTRYP)(GLuint , GLsizei , const GLdouble *))gl_get_proc(api, "glDepthRangeArrayv");
	u->core41.DepthRangeIndexed = (void (APIENTRYP)(GLuint , GLdouble , GLdouble ))gl_get_proc(api, "glDepthRangeIndexed");
	u->core41.GetFloati_v = (void (APIENTRYP)(GLenum , GLuint , GLfloat *))gl_get_proc(api, "glGetFloati_v");
	u->core41.GetDoublei_v = (void (APIENTRYP)(GLenum , GLuint , GLdouble *))gl_get_proc(api, "glGetDoublei_v");

	return core;
}

struct gl_core42 *gl_resolve_core42(struct gl_api *api, struct gl_core42 *core)
{
	union gl_combined_core42 *u = (union gl_combined_core42 *)core;
	(void)gl_resolve_core41(api, &u->core41);

	u->core42.DrawArraysInstancedBaseInstance = (void (APIENTRYP)(GLenum , GLint , GLsizei , GLsizei , GLuint ))gl_get_proc(api, "glDrawArraysInstancedBaseInstance");
	u->core42.DrawElementsInstancedBaseInstance = (void (APIENTRYP)(GLenum , GLsizei , GLenum , const void *, GLsizei , GLuint ))gl_get_proc(api, "glDrawElementsInstancedBaseInstance");
	u->core42.DrawElementsInstancedBaseVertexBaseInstance = (void (APIENTRYP)(GLenum , GLsizei , GLenum , const void *, GLsizei , GLint , GLuint ))gl_get_proc(api, "glDrawElementsInstancedBaseVertexBaseInstance");
	u->core42.GetInternalformativ = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLsizei , GLint *))gl_get_proc(api, "glGetInternalformativ");
	u->core42.GetActiveAtomicCounterBufferiv = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLint *))gl_get_proc(api, "glGetActiveAtomicCounterBufferiv");
	u->core42.BindImageTexture = (void (APIENTRYP)(GLuint , GLuint , GLint , GLboolean , GLint , GLenum , GLenum ))gl_get_proc(api, "glBindImageTexture");
	u->core42.MemoryBarrier = (void (APIENTRYP)(GLbitfield ))gl_get_proc(api, "glMemoryBarrier");
	u->core42.TexStorage1D = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei ))gl_get_proc(api, "glTexStorage1D");
	u->core42.TexStorage2D = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei , GLsizei ))gl_get_proc(api, "glTexStorage2D");
	u->core42.TexStorage3D = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei , GLsizei , GLsizei ))gl_get_proc(api, "glTexStorage3D");
	u->core42.DrawTransformFeedbackInstanced = (void (APIENTRYP)(GLenum , GLuint , GLsizei ))gl_get_proc(api, "glDrawTransformFeedbackInstanced");
	u->core42.DrawTransformFeedbackStreamInstanced = (void (APIENTRYP)(GLenum , GLuint , GLuint , GLsizei ))gl_get_proc(api, "glDrawTransformFeedbackStreamInstanced");

	return core;
}

struct gl_core43 *gl_resolve_core43(struct gl_api *api, struct gl_core43 *core)
{
	union gl_combined_core43 *u = (union gl_combined_core43 *)core;
	(void)gl_resolve_core42(api, &u->core42);

	u->core43.ClearBufferData = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLenum , const void *))gl_get_proc(api, "glClearBufferData");
	u->core43.ClearBufferSubData = (void (APIENTRYP)(GLenum , GLenum , GLintptr , GLsizeiptr , GLenum , GLenum , const void *))gl_get_proc(api, "glClearBufferSubData");
	u->core43.DispatchCompute = (void (APIENTRYP)(GLuint , GLuint , GLuint ))gl_get_proc(api, "glDispatchCompute");
	u->core43.DispatchComputeIndirect = (void (APIENTRYP)(GLintptr ))gl_get_proc(api, "glDispatchComputeIndirect");
	u->core43.CopyImageSubData = (void (APIENTRYP)(GLuint , GLenum , GLint , GLint , GLint , GLint , GLuint , GLenum , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei ))gl_get_proc(api, "glCopyImageSubData");
	u->core43.FramebufferParameteri = (void (APIENTRYP)(GLenum , GLenum , GLint ))gl_get_proc(api, "glFramebufferParameteri");
	u->core43.GetFramebufferParameteriv = (void (APIENTRYP)(GLenum , GLenum , GLint *))gl_get_proc(api, "glGetFramebufferParameteriv");
	u->core43.GetInternalformati64v = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLsizei , GLint64 *))gl_get_proc(api, "glGetInternalformati64v");
	u->core43.InvalidateTexSubImage = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei ))gl_get_proc(api, "glInvalidateTexSubImage");
	u->core43.InvalidateTexImage = (void (APIENTRYP)(GLuint , GLint ))gl_get_proc(api, "glInvalidateTexImage");
	u->core43.InvalidateBufferSubData = (void (APIENTRYP)(GLuint , GLintptr , GLsizeiptr ))gl_get_proc(api, "glInvalidateBufferSubData");
	u->core43.InvalidateBufferData = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glInvalidateBufferData");
	u->core43.InvalidateFramebuffer = (void (APIENTRYP)(GLenum , GLsizei , const GLenum *))gl_get_proc(api, "glInvalidateFramebuffer");
	u->core43.InvalidateSubFramebuffer = (void (APIENTRYP)(GLenum , GLsizei , const GLenum *, GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glInvalidateSubFramebuffer");
	u->core43.MultiDrawArraysIndirect = (void (APIENTRYP)(GLenum , const void *, GLsizei , GLsizei ))gl_get_proc(api, "glMultiDrawArraysIndirect");
	u->core43.MultiDrawElementsIndirect = (void (APIENTRYP)(GLenum , GLenum , const void *, GLsizei , GLsizei ))gl_get_proc(api, "glMultiDrawElementsIndirect");
	u->core43.GetProgramInterfaceiv = (void (APIENTRYP)(GLuint , GLenum , GLenum , GLint *))gl_get_proc(api, "glGetProgramInterfaceiv");
	u->core43.GetProgramResourceIndex = (GLuint (APIENTRYP)(GLuint , GLenum , const GLchar *))gl_get_proc(api, "glGetProgramResourceIndex");
	u->core43.GetProgramResourceName = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetProgramResourceName");
	u->core43.GetProgramResourceiv = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLsizei , const GLenum *, GLsizei , GLsizei *, GLint *))gl_get_proc(api, "glGetProgramResourceiv");
	u->core43.GetProgramResourceLocation = (GLint (APIENTRYP)(GLuint , GLenum , const GLchar *))gl_get_proc(api, "glGetProgramResourceLocation");
	u->core43.GetProgramResourceLocationIndex = (GLint (APIENTRYP)(GLuint , GLenum , const GLchar *))gl_get_proc(api, "glGetProgramResourceLocationIndex");
	u->core43.ShaderStorageBlockBinding = (void (APIENTRYP)(GLuint , GLuint , GLuint ))gl_get_proc(api, "glShaderStorageBlockBinding");
	u->core43.TexBufferRange = (void (APIENTRYP)(GLenum , GLenum , GLuint , GLintptr , GLsizeiptr ))gl_get_proc(api, "glTexBufferRange");
	u->core43.TexStorage2DMultisample = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei , GLsizei , GLboolean ))gl_get_proc(api, "glTexStorage2DMultisample");
	u->core43.TexStorage3DMultisample = (void (APIENTRYP)(GLenum , GLsizei , GLenum , GLsizei , GLsizei , GLsizei , GLboolean ))gl_get_proc(api, "glTexStorage3DMultisample");
	u->core43.TextureView = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLenum , GLuint , GLuint , GLuint , GLuint ))gl_get_proc(api, "glTextureView");
	u->core43.BindVertexBuffer = (void (APIENTRYP)(GLuint , GLuint , GLintptr , GLsizei ))gl_get_proc(api, "glBindVertexBuffer");
	u->core43.VertexAttribFormat = (void (APIENTRYP)(GLuint , GLint , GLenum , GLboolean , GLuint ))gl_get_proc(api, "glVertexAttribFormat");
	u->core43.VertexAttribIFormat = (void (APIENTRYP)(GLuint , GLint , GLenum , GLuint ))gl_get_proc(api, "glVertexAttribIFormat");
	u->core43.VertexAttribLFormat = (void (APIENTRYP)(GLuint , GLint , GLenum , GLuint ))gl_get_proc(api, "glVertexAttribLFormat");
	u->core43.VertexAttribBinding = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glVertexAttribBinding");
	u->core43.VertexBindingDivisor = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glVertexBindingDivisor");
	u->core43.DebugMessageControl = (void (APIENTRYP)(GLenum , GLenum , GLenum , GLsizei , const GLuint *, GLboolean ))gl_get_proc(api, "glDebugMessageControl");
	u->core43.DebugMessageInsert = (void (APIENTRYP)(GLenum , GLenum , GLuint , GLenum , GLsizei , const GLchar *))gl_get_proc(api, "glDebugMessageInsert");
	u->core43.DebugMessageCallback = (void (APIENTRYP)(GLDEBUGPROC , const void *))gl_get_proc(api, "glDebugMessageCallback");
	u->core43.GetDebugMessageLog = (GLuint (APIENTRYP)(GLuint , GLsizei , GLenum *, GLenum *, GLuint *, GLenum *, GLsizei *, GLchar *))gl_get_proc(api, "glGetDebugMessageLog");
	u->core43.PushDebugGroup = (void (APIENTRYP)(GLenum , GLuint , GLsizei , const GLchar *))gl_get_proc(api, "glPushDebugGroup");
	u->core43.PopDebugGroup = (void (APIENTRYP)(void))gl_get_proc(api, "glPopDebugGroup");
	u->core43.ObjectLabel = (void (APIENTRYP)(GLenum , GLuint , GLsizei , const GLchar *))gl_get_proc(api, "glObjectLabel");
	u->core43.GetObjectLabel = (void (APIENTRYP)(GLenum , GLuint , GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetObjectLabel");
	u->core43.ObjectPtrLabel = (void (APIENTRYP)(const void *, GLsizei , const GLchar *))gl_get_proc(api, "glObjectPtrLabel");
	u->core43.GetObjectPtrLabel = (void (APIENTRYP)(const void *, GLsizei , GLsizei *, GLchar *))gl_get_proc(api, "glGetObjectPtrLabel");
	u->core43.GetPointerv = (void (APIENTRYP)(GLenum , void **))gl_get_proc(api, "glGetPointerv");

	return core;
}

struct gl_core44 *gl_resolve_core44(struct gl_api *api, struct gl_core44 *core)
{
	union gl_combined_core44 *u = (union gl_combined_core44 *)core;
	(void)gl_resolve_core43(api, &u->core43);

	u->core44.BufferStorage = (void (APIENTRYP)(GLenum , GLsizeiptr , const void *, GLbitfield ))gl_get_proc(api, "glBufferStorage");
	u->core44.ClearTexImage = (void (APIENTRYP)(GLuint , GLint , GLenum , GLenum , const void *))gl_get_proc(api, "glClearTexImage");
	u->core44.ClearTexSubImage = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei , GLenum , GLenum , const void *))gl_get_proc(api, "glClearTexSubImage");
	u->core44.BindBuffersBase = (void (APIENTRYP)(GLenum , GLuint , GLsizei , const GLuint *))gl_get_proc(api, "glBindBuffersBase");
	u->core44.BindBuffersRange = (void (APIENTRYP)(GLenum , GLuint , GLsizei , const GLuint *, const GLintptr *, const GLsizeiptr *))gl_get_proc(api, "glBindBuffersRange");
	u->core44.BindTextures = (void (APIENTRYP)(GLuint , GLsizei , const GLuint *))gl_get_proc(api, "glBindTextures");
	u->core44.BindSamplers = (void (APIENTRYP)(GLuint , GLsizei , const GLuint *))gl_get_proc(api, "glBindSamplers");
	u->core44.BindImageTextures = (void (APIENTRYP)(GLuint , GLsizei , const GLuint *))gl_get_proc(api, "glBindImageTextures");
	u->core44.BindVertexBuffers = (void (APIENTRYP)(GLuint , GLsizei , const GLuint *, const GLintptr *, const GLsizei *))gl_get_proc(api, "glBindVertexBuffers");

	return core;
}

struct gl_core45 *gl_resolve_core45(struct gl_api *api, struct gl_core45 *core)
{
	union gl_combined_core45 *u = (union gl_combined_core45 *)core;
	(void)gl_resolve_core44(api, &u->core44);

	u->core45.ClipControl = (void (APIENTRYP)(GLenum , GLenum ))gl_get_proc(api, "glClipControl");
	u->core45.CreateTransformFeedbacks = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glCreateTransformFeedbacks");
	u->core45.TransformFeedbackBufferBase = (void (APIENTRYP)(GLuint , GLuint , GLuint ))gl_get_proc(api, "glTransformFeedbackBufferBase");
	u->core45.TransformFeedbackBufferRange = (void (APIENTRYP)(GLuint , GLuint , GLuint , GLintptr , GLsizeiptr ))gl_get_proc(api, "glTransformFeedbackBufferRange");
	u->core45.GetTransformFeedbackiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetTransformFeedbackiv");
	u->core45.GetTransformFeedbacki_v = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLint *))gl_get_proc(api, "glGetTransformFeedbacki_v");
	u->core45.GetTransformFeedbacki64_v = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLint64 *))gl_get_proc(api, "glGetTransformFeedbacki64_v");
	u->core45.CreateBuffers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glCreateBuffers");
	u->core45.NamedBufferStorage = (void (APIENTRYP)(GLuint , GLsizeiptr , const void *, GLbitfield ))gl_get_proc(api, "glNamedBufferStorage");
	u->core45.NamedBufferData = (void (APIENTRYP)(GLuint , GLsizeiptr , const void *, GLenum ))gl_get_proc(api, "glNamedBufferData");
	u->core45.NamedBufferSubData = (void (APIENTRYP)(GLuint , GLintptr , GLsizeiptr , const void *))gl_get_proc(api, "glNamedBufferSubData");
	u->core45.CopyNamedBufferSubData = (void (APIENTRYP)(GLuint , GLuint , GLintptr , GLintptr , GLsizeiptr ))gl_get_proc(api, "glCopyNamedBufferSubData");
	u->core45.ClearNamedBufferData = (void (APIENTRYP)(GLuint , GLenum , GLenum , GLenum , const void *))gl_get_proc(api, "glClearNamedBufferData");
	u->core45.ClearNamedBufferSubData = (void (APIENTRYP)(GLuint , GLenum , GLintptr , GLsizeiptr , GLenum , GLenum , const void *))gl_get_proc(api, "glClearNamedBufferSubData");
	u->core45.MapNamedBuffer = (void *(APIENTRYP)(GLuint , GLenum ))gl_get_proc(api, "glMapNamedBuffer");
	u->core45.MapNamedBufferRange = (void *(APIENTRYP)(GLuint , GLintptr , GLsizeiptr , GLbitfield ))gl_get_proc(api, "glMapNamedBufferRange");
	u->core45.UnmapNamedBuffer = (GLboolean (APIENTRYP)(GLuint ))gl_get_proc(api, "glUnmapNamedBuffer");
	u->core45.FlushMappedNamedBufferRange = (void (APIENTRYP)(GLuint , GLintptr , GLsizeiptr ))gl_get_proc(api, "glFlushMappedNamedBufferRange");
	u->core45.GetNamedBufferParameteriv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetNamedBufferParameteriv");
	u->core45.GetNamedBufferParameteri64v = (void (APIENTRYP)(GLuint , GLenum , GLint64 *))gl_get_proc(api, "glGetNamedBufferParameteri64v");
	u->core45.GetNamedBufferPointerv = (void (APIENTRYP)(GLuint , GLenum , void **))gl_get_proc(api, "glGetNamedBufferPointerv");
	u->core45.GetNamedBufferSubData = (void (APIENTRYP)(GLuint , GLintptr , GLsizeiptr , void *))gl_get_proc(api, "glGetNamedBufferSubData");
	u->core45.CreateFramebuffers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glCreateFramebuffers");
	u->core45.NamedFramebufferRenderbuffer = (void (APIENTRYP)(GLuint , GLenum , GLenum , GLuint ))gl_get_proc(api, "glNamedFramebufferRenderbuffer");
	u->core45.NamedFramebufferParameteri = (void (APIENTRYP)(GLuint , GLenum , GLint ))gl_get_proc(api, "glNamedFramebufferParameteri");
	u->core45.NamedFramebufferTexture = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLint ))gl_get_proc(api, "glNamedFramebufferTexture");
	u->core45.NamedFramebufferTextureLayer = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLint , GLint ))gl_get_proc(api, "glNamedFramebufferTextureLayer");
	u->core45.NamedFramebufferDrawBuffer = (void (APIENTRYP)(GLuint , GLenum ))gl_get_proc(api, "glNamedFramebufferDrawBuffer");
	u->core45.NamedFramebufferDrawBuffers = (void (APIENTRYP)(GLuint , GLsizei , const GLenum *))gl_get_proc(api, "glNamedFramebufferDrawBuffers");
	u->core45.NamedFramebufferReadBuffer = (void (APIENTRYP)(GLuint , GLenum ))gl_get_proc(api, "glNamedFramebufferReadBuffer");
	u->core45.InvalidateNamedFramebufferData = (void (APIENTRYP)(GLuint , GLsizei , const GLenum *))gl_get_proc(api, "glInvalidateNamedFramebufferData");
	u->core45.InvalidateNamedFramebufferSubData = (void (APIENTRYP)(GLuint , GLsizei , const GLenum *, GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glInvalidateNamedFramebufferSubData");
	u->core45.ClearNamedFramebufferiv = (void (APIENTRYP)(GLuint , GLenum , GLint , const GLint *))gl_get_proc(api, "glClearNamedFramebufferiv");
	u->core45.ClearNamedFramebufferuiv = (void (APIENTRYP)(GLuint , GLenum , GLint , const GLuint *))gl_get_proc(api, "glClearNamedFramebufferuiv");
	u->core45.ClearNamedFramebufferfv = (void (APIENTRYP)(GLuint , GLenum , GLint , const GLfloat *))gl_get_proc(api, "glClearNamedFramebufferfv");
	u->core45.ClearNamedFramebufferfi = (void (APIENTRYP)(GLuint , GLenum , GLint , GLfloat , GLint ))gl_get_proc(api, "glClearNamedFramebufferfi");
	u->core45.BlitNamedFramebuffer = (void (APIENTRYP)(GLuint , GLuint , GLint , GLint , GLint , GLint , GLint , GLint , GLint , GLint , GLbitfield , GLenum ))gl_get_proc(api, "glBlitNamedFramebuffer");
	u->core45.CheckNamedFramebufferStatus = (GLenum (APIENTRYP)(GLuint , GLenum ))gl_get_proc(api, "glCheckNamedFramebufferStatus");
	u->core45.GetNamedFramebufferParameteriv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetNamedFramebufferParameteriv");
	u->core45.GetNamedFramebufferAttachmentParameteriv = (void (APIENTRYP)(GLuint , GLenum , GLenum , GLint *))gl_get_proc(api, "glGetNamedFramebufferAttachmentParameteriv");
	u->core45.CreateRenderbuffers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glCreateRenderbuffers");
	u->core45.NamedRenderbufferStorage = (void (APIENTRYP)(GLuint , GLenum , GLsizei , GLsizei ))gl_get_proc(api, "glNamedRenderbufferStorage");
	u->core45.NamedRenderbufferStorageMultisample = (void (APIENTRYP)(GLuint , GLsizei , GLenum , GLsizei , GLsizei ))gl_get_proc(api, "glNamedRenderbufferStorageMultisample");
	u->core45.GetNamedRenderbufferParameteriv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetNamedRenderbufferParameteriv");
	u->core45.CreateTextures = (void (APIENTRYP)(GLenum , GLsizei , GLuint *))gl_get_proc(api, "glCreateTextures");
	u->core45.TextureBuffer = (void (APIENTRYP)(GLuint , GLenum , GLuint ))gl_get_proc(api, "glTextureBuffer");
	u->core45.TextureBufferRange = (void (APIENTRYP)(GLuint , GLenum , GLuint , GLintptr , GLsizeiptr ))gl_get_proc(api, "glTextureBufferRange");
	u->core45.TextureStorage1D = (void (APIENTRYP)(GLuint , GLsizei , GLenum , GLsizei ))gl_get_proc(api, "glTextureStorage1D");
	u->core45.TextureStorage2D = (void (APIENTRYP)(GLuint , GLsizei , GLenum , GLsizei , GLsizei ))gl_get_proc(api, "glTextureStorage2D");
	u->core45.TextureStorage3D = (void (APIENTRYP)(GLuint , GLsizei , GLenum , GLsizei , GLsizei , GLsizei ))gl_get_proc(api, "glTextureStorage3D");
	u->core45.TextureStorage2DMultisample = (void (APIENTRYP)(GLuint , GLsizei , GLenum , GLsizei , GLsizei , GLboolean ))gl_get_proc(api, "glTextureStorage2DMultisample");
	u->core45.TextureStorage3DMultisample = (void (APIENTRYP)(GLuint , GLsizei , GLenum , GLsizei , GLsizei , GLsizei , GLboolean ))gl_get_proc(api, "glTextureStorage3DMultisample");
	u->core45.TextureSubImage1D = (void (APIENTRYP)(GLuint , GLint , GLint , GLsizei , GLenum , GLenum , const void *))gl_get_proc(api, "glTextureSubImage1D");
	u->core45.TextureSubImage2D = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLsizei , GLsizei , GLenum , GLenum , const void *))gl_get_proc(api, "glTextureSubImage2D");
	u->core45.TextureSubImage3D = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei , GLenum , GLenum , const void *))gl_get_proc(api, "glTextureSubImage3D");
	u->core45.CompressedTextureSubImage1D = (void (APIENTRYP)(GLuint , GLint , GLint , GLsizei , GLenum , GLsizei , const void *))gl_get_proc(api, "glCompressedTextureSubImage1D");
	u->core45.CompressedTextureSubImage2D = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLsizei , GLsizei , GLenum , GLsizei , const void *))gl_get_proc(api, "glCompressedTextureSubImage2D");
	u->core45.CompressedTextureSubImage3D = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei , GLenum , GLsizei , const void *))gl_get_proc(api, "glCompressedTextureSubImage3D");
	u->core45.CopyTextureSubImage1D = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLsizei ))gl_get_proc(api, "glCopyTextureSubImage1D");
	u->core45.CopyTextureSubImage2D = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glCopyTextureSubImage2D");
	u->core45.CopyTextureSubImage3D = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLint , GLint , GLsizei , GLsizei ))gl_get_proc(api, "glCopyTextureSubImage3D");
	u->core45.TextureParameterf = (void (APIENTRYP)(GLuint , GLenum , GLfloat ))gl_get_proc(api, "glTextureParameterf");
	u->core45.TextureParameterfv = (void (APIENTRYP)(GLuint , GLenum , const GLfloat *))gl_get_proc(api, "glTextureParameterfv");
	u->core45.TextureParameteri = (void (APIENTRYP)(GLuint , GLenum , GLint ))gl_get_proc(api, "glTextureParameteri");
	u->core45.TextureParameterIiv = (void (APIENTRYP)(GLuint , GLenum , const GLint *))gl_get_proc(api, "glTextureParameterIiv");
	u->core45.TextureParameterIuiv = (void (APIENTRYP)(GLuint , GLenum , const GLuint *))gl_get_proc(api, "glTextureParameterIuiv");
	u->core45.TextureParameteriv = (void (APIENTRYP)(GLuint , GLenum , const GLint *))gl_get_proc(api, "glTextureParameteriv");
	u->core45.GenerateTextureMipmap = (void (APIENTRYP)(GLuint ))gl_get_proc(api, "glGenerateTextureMipmap");
	u->core45.BindTextureUnit = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glBindTextureUnit");
	u->core45.GetTextureImage = (void (APIENTRYP)(GLuint , GLint , GLenum , GLenum , GLsizei , void *))gl_get_proc(api, "glGetTextureImage");
	u->core45.GetCompressedTextureImage = (void (APIENTRYP)(GLuint , GLint , GLsizei , void *))gl_get_proc(api, "glGetCompressedTextureImage");
	u->core45.GetTextureLevelParameterfv = (void (APIENTRYP)(GLuint , GLint , GLenum , GLfloat *))gl_get_proc(api, "glGetTextureLevelParameterfv");
	u->core45.GetTextureLevelParameteriv = (void (APIENTRYP)(GLuint , GLint , GLenum , GLint *))gl_get_proc(api, "glGetTextureLevelParameteriv");
	u->core45.GetTextureParameterfv = (void (APIENTRYP)(GLuint , GLenum , GLfloat *))gl_get_proc(api, "glGetTextureParameterfv");
	u->core45.GetTextureParameterIiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetTextureParameterIiv");
	u->core45.GetTextureParameterIuiv = (void (APIENTRYP)(GLuint , GLenum , GLuint *))gl_get_proc(api, "glGetTextureParameterIuiv");
	u->core45.GetTextureParameteriv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetTextureParameteriv");
	u->core45.CreateVertexArrays = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glCreateVertexArrays");
	u->core45.DisableVertexArrayAttrib = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glDisableVertexArrayAttrib");
	u->core45.EnableVertexArrayAttrib = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glEnableVertexArrayAttrib");
	u->core45.VertexArrayElementBuffer = (void (APIENTRYP)(GLuint , GLuint ))gl_get_proc(api, "glVertexArrayElementBuffer");
	u->core45.VertexArrayVertexBuffer = (void (APIENTRYP)(GLuint , GLuint , GLuint , GLintptr , GLsizei ))gl_get_proc(api, "glVertexArrayVertexBuffer");
	u->core45.VertexArrayVertexBuffers = (void (APIENTRYP)(GLuint , GLuint , GLsizei , const GLuint *, const GLintptr *, const GLsizei *))gl_get_proc(api, "glVertexArrayVertexBuffers");
	u->core45.VertexArrayAttribBinding = (void (APIENTRYP)(GLuint , GLuint , GLuint ))gl_get_proc(api, "glVertexArrayAttribBinding");
	u->core45.VertexArrayAttribFormat = (void (APIENTRYP)(GLuint , GLuint , GLint , GLenum , GLboolean , GLuint ))gl_get_proc(api, "glVertexArrayAttribFormat");
	u->core45.VertexArrayAttribIFormat = (void (APIENTRYP)(GLuint , GLuint , GLint , GLenum , GLuint ))gl_get_proc(api, "glVertexArrayAttribIFormat");
	u->core45.VertexArrayAttribLFormat = (void (APIENTRYP)(GLuint , GLuint , GLint , GLenum , GLuint ))gl_get_proc(api, "glVertexArrayAttribLFormat");
	u->core45.VertexArrayBindingDivisor = (void (APIENTRYP)(GLuint , GLuint , GLuint ))gl_get_proc(api, "glVertexArrayBindingDivisor");
	u->core45.GetVertexArrayiv = (void (APIENTRYP)(GLuint , GLenum , GLint *))gl_get_proc(api, "glGetVertexArrayiv");
	u->core45.GetVertexArrayIndexediv = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLint *))gl_get_proc(api, "glGetVertexArrayIndexediv");
	u->core45.GetVertexArrayIndexed64iv = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLint64 *))gl_get_proc(api, "glGetVertexArrayIndexed64iv");
	u->core45.CreateSamplers = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glCreateSamplers");
	u->core45.CreateProgramPipelines = (void (APIENTRYP)(GLsizei , GLuint *))gl_get_proc(api, "glCreateProgramPipelines");
	u->core45.CreateQueries = (void (APIENTRYP)(GLenum , GLsizei , GLuint *))gl_get_proc(api, "glCreateQueries");
	u->core45.GetQueryBufferObjecti64v = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLintptr ))gl_get_proc(api, "glGetQueryBufferObjecti64v");
	u->core45.GetQueryBufferObjectiv = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLintptr ))gl_get_proc(api, "glGetQueryBufferObjectiv");
	u->core45.GetQueryBufferObjectui64v = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLintptr ))gl_get_proc(api, "glGetQueryBufferObjectui64v");
	u->core45.GetQueryBufferObjectuiv = (void (APIENTRYP)(GLuint , GLuint , GLenum , GLintptr ))gl_get_proc(api, "glGetQueryBufferObjectuiv");
	u->core45.MemoryBarrierByRegion = (void (APIENTRYP)(GLbitfield ))gl_get_proc(api, "glMemoryBarrierByRegion");
	u->core45.GetTextureSubImage = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei , GLenum , GLenum , GLsizei , void *))gl_get_proc(api, "glGetTextureSubImage");
	u->core45.GetCompressedTextureSubImage = (void (APIENTRYP)(GLuint , GLint , GLint , GLint , GLint , GLsizei , GLsizei , GLsizei , GLsizei , void *))gl_get_proc(api, "glGetCompressedTextureSubImage");
	u->core45.GetGraphicsResetStatus = (GLenum (APIENTRYP)(void))gl_get_proc(api, "glGetGraphicsResetStatus");
	u->core45.GetnCompressedTexImage = (void (APIENTRYP)(GLenum , GLint , GLsizei , void *))gl_get_proc(api, "glGetnCompressedTexImage");
	u->core45.GetnTexImage = (void (APIENTRYP)(GLenum , GLint , GLenum , GLenum , GLsizei , void *))gl_get_proc(api, "glGetnTexImage");
	u->core45.GetnUniformdv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLdouble *))gl_get_proc(api, "glGetnUniformdv");
	u->core45.GetnUniformfv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLfloat *))gl_get_proc(api, "glGetnUniformfv");
	u->core45.GetnUniformiv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLint *))gl_get_proc(api, "glGetnUniformiv");
	u->core45.GetnUniformuiv = (void (APIENTRYP)(GLuint , GLint , GLsizei , GLuint *))gl_get_proc(api, "glGetnUniformuiv");
	u->core45.ReadnPixels = (void (APIENTRYP)(GLint , GLint , GLsizei , GLsizei , GLenum , GLenum , GLsizei , void *))gl_get_proc(api, "glReadnPixels");
	u->core45.TextureBarrier = (void (APIENTRYP)(void))gl_get_proc(api, "glTextureBarrier");

	return core;
}
